replicaCount: 1

image:
  repository: ecomacrnet9.azurecr.io/basket
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

env:
  ASPNETCORE_ENVIRONMENT: "Development"
  ElasticConfiguration__Uri: "http://elasticsearch:9200"
  GrpcSettings__DiscountUrl: "http://discountapi:8080"

# KeyVault (redis + jwt)
keyVault:
  enabled: true
  name: ecom-kv-net9
  tenantId: 02d34192-5027-485f-9f55-c9b0f9a34e6f
  userAssignedIdentityID: c8d1b9d4-5c68-4859-a545-947b4deafe3b
  resourceGroup: rg-ecommerce
  subscriptionId: 18c0cdf7-3490-488d-9080-82609b1ac3f8

  secrets:
    - name: RedisCacheConnection
      alias: RedisCacheConnection

    - name: JwtKey
      alias: JwtKey

eventBus:
  secretName: rabbitmq-secret
  secretKey: rabbitmqconnection

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
