apiVersion: v1
kind: Secret
metadata:
  name: identity-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  identityConnectionString: {{ .Values.identityConnectionString | quote }}
  jwtKey: "super_secure_secret_key_1234567890!@#"
