{{- if .Values.keyVault.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-secrets
  namespace: {{ .Release.Namespace }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "{{ .Values.keyVault.userAssignedIdentityID }}"
    keyvaultName: "{{ .Values.keyVault.name }}"
    tenantId: "{{ .Values.keyVault.tenantId }}"
    resourceGroup: "{{ .Values.keyVault.resourceGroup }}"
    subscriptionId: "{{ .Values.keyVault.subscriptionId }}"
    cloudName: ""

    objects: |
      array:
        {{- range .Values.keyVault.secrets }}
        - |
          objectName: "{{ .name }}"
          objectType: secret
          objectAlias: "{{ .alias }}"
        {{- end }}

  secretObjects:
    {{- range .Values.keyVault.secrets }}
    - secretName: {{ .alias }}
      type: Opaque
      data:
        - key: {{ .alias }}
          objectName: "{{ .alias }}" # important fix
    {{- end }}

{{- end }}
