apiVersion: apps/v1
kind: Deployment
metadata:
  name: discountapi
  namespace: {{ .Release.Namespace }}
  labels:
    app: discountapi
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: discountapi
  template:
    metadata:
      labels:
        app: discountapi
    spec:
      containers:
        - name: discountapi
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: 8080

          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: {{ .Values.env.ASPNETCORE_ENVIRONMENT | quote }}

            - name: DatabaseSettings__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: {{ .Values.secret.key }}

          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true

      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: discount-kv-secrets
