apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: discount-kv-secrets
  namespace: {{ .Release.Namespace }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.keyVault.userAssignedIdentityID }}
    keyvaultName: {{ .Values.keyVault.name }}
    tenantId: {{ .Values.keyVault.tenantId }}

    objects: |
      array:
        - |
          objectName: {{ .Values.secret.kvObjectName }}
          objectType: secret

  secretObjects:
    - secretName: {{ .Values.secret.name }}
      type: Opaque
      data:
        - objectName: {{ .Values.secret.kvObjectName }}
          key: {{ .Values.secret.key }}
