apiVersion: v1
kind: Service
metadata:
  name: {{ include "discountapi.fullname" . }}
  labels:
    app: discountapi
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: 8080
  selector:
    app: discountapi
