apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver-identity
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver-identity
  template:
    metadata:
      labels:
        app: sqlserver-identity
    spec:
      securityContext:
        fsGroup: 10001
      containers:
        - name: sqlserver-identity
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: 1433

          env:
            - name: ACCEPT_EULA
              value: "Y"

            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sqlserver-identity-secret
                  key: SA_PASSWORD

            - name: MSSQL_PID
              value: "Developer"

          volumeMounts:
            - name: mssqldata
              mountPath: /var/opt/mssql

          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "3Gi"
              cpu: "1"

      volumes:
        - name: mssqldata
          persistentVolumeClaim:
            claimName: sqlserver-identity-pvc
