apiVersion: v1
kind: Service
metadata:
  name: sqlserver-identity
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 1433
      protocol: TCP
  selector:
    app: sqlserver-identity
