replicaCount: 1

image:
  repository: ecomacrnet9.azurecr.io/identity
  tag: "latest"
  pullPolicy: Always

env:
  ASPNETCORE_ENVIRONMENT: "Development"

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

secret:
  name: identity-secrets
  connectionKey: identityConnectionString
  jwtKey: jwtKey

jwt:
  issuer: "ecommerce.identity"
  audience: "ecommerce.clients"
  duration: "60"
