apiVersion: v1
kind: Service
metadata:
  name: paymentapi
  namespace: {{ .Release.Namespace }}

spec:
  type: {{ .Values.service.type }}
  selector:
    app: paymentapi

  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
