apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  rabbitmqconnection: "amqp://{{ .Values.rabbitmq.username }}:{{ .Values.rabbitmq.password }}@{{ .Release.Name }}:{{ .Values.service.amqpPort }}/"
