apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}

  ports:
    - name: amqp
      port: {{ .Values.service.amqpPort }}
      targetPort: 5672

    - name: management
      port: {{ .Values.service.managementPort }}
      targetPort: 15672
