image:
  repository: mcr.microsoft.com/mssql/server
  tag: "2022-latest"
  pullPolicy: IfNotPresent

saPassword: "YourStrongPassword123!"

persistence:
  enabled: true
  size: 10Gi
  storageClass: ""

service:
  port: 1433
